server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
        - id: payment-service"
          uri: http://localhost:8083
          predicates:
            - Path=/api/payments/**
        - id: transfer-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/transfers/**
        - id: loan-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/loans/**
